### ISSUE TITLE
页面导入直接页面加载不了，也没有报错，是因为我得项目不是TS得原因嘛？

### ISSUE THREAD

**Issue by duobancc** [PengChen96/table-xlsx#1]
页面渲染不出来，注释掉，就正常了
![image](https://user-images.githubusercontent.com/37232082/165056291-df895bbb-c495-423f-9c21-1208f48b5918.png)

**Comment by PengChen96** [comment]
您好，这个跟项目是否是TS是没关系的，可以先试下这样引入能不能正常使用 `import { exportFile } from "table-xlsx/dist/table-xlsx.production";`
另外，项目使用的是webpack吗，方便提供下版本号吗。
最后感谢你的issues

**Comment by duobancc** [comment]
> 您好，这个跟项目是否是TS是没关系的，可以先试下这样引入能不能正常使用 `import { exportFile } from "table-xlsx/dist/table-xlsx.production";` 另外，项目使用的是webpack吗，方便提供下版本号吗。 最后感谢你的issues

早上换这个导入方式成功了，然后我的webpack版本 
![image](https://user-images.githubusercontent.com/37232082/165199151-7cd654c0-1364-47c5-ae13-7c596e07f302.png)

**Comment by PengChen96** [comment]
好的，我晚点修复下，你先按这种方式使用。还有问题或者有什么需求不满足的可以再联系我。

**Comment by duobancc** [comment]
> 

好哒，感谢
