### ISSUE TITLE
语序错乱

### ISSUE THREAD

**Issue by erlonghuhaoge** [PengChen96/table-xlsx#10]
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/eeb65993-225c-415f-bd21-2db0569a7e05)
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/67463adc-b9a5-414c-b2ac-d778ddf6c369)
具体时间和末尾的句号都被提到前边了，大佬有时间帮忙看下

**Comment by erlonghuhaoge** [comment]
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/531e5374-7d9e-4299-8b6e-9fcd0c0747fb)
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/1fe81a26-c8ad-45ed-b630-95b9224c79a0)
在这里也出现了同样的情况

**Comment by erlonghuhaoge** [comment]
用朋友的mac试了下是正常的，windows才会出现这种状况

**Comment by PengChen96** [comment]
会不会是Excel的设置问题，或者你用wps打开试试看。然后我试试windows打开看看。

**Comment by erlonghuhaoge** [comment]
抱歉，应该是Excel的问题，我把我导出的Excel发给朋友，他那边打开就没事。。

**Comment by PengChen96** [comment]
好的，那你看看是设置了哪里会出现这种情况，解决了可以发这里看看😄。

**Comment by erlonghuhaoge** [comment]
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/26fcb9b2-1314-465d-9b23-db513281a0bc)
我的Excel默认的文本对齐是从右到左，但是不知道为啥只有符号是倒叙，懵了。。

**Comment by PengChen96** [comment]
这个文字方向改为从左到右会显示正常吗，我这点Excel版本还没有这个设置。[捂脸]

**Comment by erlonghuhaoge** [comment]
改之后就正常了，我现在用的这个Excel属实有点反人类。。

**Comment by PengChen96** [comment]
哈哈，你这个是哪个版本

**Comment by erlonghuhaoge** [comment]
![image](https://github.com/PengChen96/table-xlsx/assets/20678391/2d0c2ec3-fa11-41cd-aac5-28b34ffa4cc4)
领工作机的时候就带着这个，也没注意会有这么奇葩。 [捂脸]

**Comment by PengChen96** [comment]
嗯嗯，后面我下个试试。

**Comment by erlonghuhaoge** [comment]
感谢大佬，这个做不做兼容应该都可以的吧
其实更建议换一个正常点的excel使用，不然每次手动修改文本方向也闹心
Issues我先关了哈
