### ISSUE TITLE
你好想问下如图的宽度怎么设置默认下面的编辑器宽，看文档好像没有参数设置项

### ISSUE THREAD

**Issue by ngwszsd** [PengChen96/table-xlsx#12]
![image](https://github.com/PengChen96/table-xlsx/assets/45424459/5cfba92f-a742-4e78-87d5-8de2f72fe294)

**Comment by PengChen96** [comment]
你是说行高吗，列宽的话是用的columns里的width

**Comment by ngwszsd** [comment]
> 你是说行高吗，列宽的话是用的columns里的width

就是行高不知道怎么设置 列宽看到设置参数了

**Comment by PengChen96** [comment]
行高现在是不能设置，你是什么场景需要，我可以加一下

**Comment by ngwszsd** [comment]
就是产品提的 也没什么影响其实

**Comment by ngwszsd** [comment]
> 行高现在是不能设置，你是什么场景需要，我可以加一下


就是产品提的 也没什么影响其实

**Comment by PengChen96** [comment]
你是想所有的行高都一样是吧，这个不知道sheetjs有没有参数设置，我去看看文档。不过也有个差点的方法，就是往dataSource后面插入一些空数据。

**Comment by ngwszsd** [comment]
> 你是想所有的行高都一样是吧，这个不知道sheetjs有没有参数设置，我去看看文档。不过也有个差点的方法，就是往dataSource后面插入一些空数据。

![image](https://github.com/PengChen96/table-xlsx/assets/45424459/a32bda48-e30c-4ae2-8183-1ff8a5285e82)
sheets工作表对象上有的

**Comment by PengChen96** [comment]
这个我知道的，他数组里的一个对象是只设置里一行的

**Comment by ngwszsd** [comment]
行吧 我也有一个自己封装的 用那个把先

**Comment by PengChen96** [comment]
嗯嗯，你那个可以设置所有行高吗，是基于sheetjs的吗

**Comment by ngwszsd** [comment]
> 嗯嗯，你那个可以设置所有行高吗，是基于sheetjs的吗

写的方法 定制化场景比较多 就把工作表对象暴露出来了

**Comment by PengChen96** [comment]
喔喔，好的
