### ISSUE TITLE
解析时报错：table-xlsx.production.js，升级不到0.1.9，react和react-dom都是16.14 antd是最新的v4

### ISSUE THREAD

**Issue by ngwszsd** [PengChen96/table-xlsx#13]
![image](https://github.com/PengChen96/table-xlsx/assets/45424459/cd2b3028-04bc-401f-812e-c4712165a958)

**Comment by ngwszsd** [comment]
刚看了以前的issure 要升级到0.1.9，但是只有0.1.8最高选项是为什么呀 ， 我用vite新开了个项目就能有0.1.9
![image](https://github.com/PengChen96/table-xlsx/assets/45424459/cd7b308b-a370-470c-8f45-255ce3a578a4)

**Comment by PengChen96** [comment]
你应该用的是公司的npm私库吧，你可以在项目里.npmrc文件中看看

**Comment by ngwszsd** [comment]
e

> 你应该用的是公司的npm私库吧，你可以在项目里.npmrc文件中看看

我日还真是谁加的她妹的
