### ISSUE TITLE
可否暴露一些工具函数、对象，例如formatToSheet、wb，方便独立调用

### ISSUE THREAD

**Issue by Feather130** [PengChen96/table-xlsx#17]
现在项目再用webworker做导出，有些windows上的方法无法使用，希望可以暴露一些方法，可以组合使用

**Comment by PengChen96** [comment]
你是想使用库里的内部方法吗，我可以暴露一下，不过我有点不明白，使用exportFile是会报错吗

**Comment by Feather130** [comment]
是的，xlsx.writeFile方法里会有调用window下面的方法，webworker里访问不了window

**Comment by Feather130** [comment]
可以

**Comment by Feather130** [comment]
可以了，谢谢🤞

**Comment by PengChen96** [comment]
OK，客气啦🌹
