### ISSUE TITLE
cdn是不是没用了，请求失败了

### ISSUE THREAD

**Issue by YouCannotReadMe** [PengChen96/table-xlsx#18]
ReferenceError: exportFile is not defined
    at Proxy.exportComplexUtils (page.js:1101:3)

**Comment by PengChen96** [comment]
可能是加载慢，用https://www.jsdelivr.com/package/npm/table-xlsx?tab=files&path=dist这个会好一些

**Comment by YouCannotReadMe** [comment]
这个怎么用呢也是cdn吗，我之前用的是https://unpkg.com/table-xlsx/dist/table-xlsx.production.umd.js这个，之前好好的，现在请求失败了，[https://www.jsdelivr.com/package/npm/table-xlsx?tab=files&path=dist这个会好一些]，这个是什么意思呢

**Comment by PengChen96** [comment]
一样的，就是换个域名，https://cdn.jsdelivr.net/npm/table-xlsx/dist/table-xlsx.production.umd.js

**Comment by YouCannotReadMe** [comment]
好的，谢谢大哥

**Comment by PengChen96** [comment]
客气啦

**Comment by YouCannotReadMe** [comment]
有群吗，我觉得大哥写的非常好

**Comment by PengChen96** [comment]
目前没群😂，觉得还不错的话，点个star吧 哈哈哈

**Comment by YouCannotReadMe** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengChen96/table-xlsx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月14日(星期四) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengChen96/table-xlsx] cdn是不是没用了，请求失败了 (Issue #18)





 
客气啦

**Comment by YouCannotReadMe** [comment]
哥，我这边在钉钉客户端里面用了你这个导出插件，导出的 文件 名没有默认都不是xlsx格式的，在浏览器就不会出现这个问题，这是什么问题呢，有什么解决办法吗，因为我这边用xlsx.js插件是没有这个问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengChen96/table-xlsx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月14日(星期四) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengChen96/table-xlsx] cdn是不是没用了，请求失败了 (Issue #18)





 
目前没群😂，觉得还不错的话，点个star吧 哈哈哈

**Comment by PengChen96** [comment]
filename设置成xxx.xlsx了嘛

**Comment by YouCannotReadMe** [comment]
设置了，在浏览器导出 是这样的，没问题的，但是在钉钉里面就是下面这样的

我下面用xlsx.full.js插件不会有这个问题，浏览器钉钉都没问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PengChen96/table-xlsx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月10日(星期六) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PengChen96/table-xlsx] cdn是不是没用了，请求失败了 (Issue #18)





 
filename设置成xxx.xlsx了嘛
