### ISSUE TITLE
打包到dev，导出文件直接是已损坏的

### ISSUE THREAD

**Issue by duobancc** [PengChen96/table-xlsx#2]
项目本身存在xlsx ，这个会影响不？

**Comment by PengChen96** [comment]
是导出的excel文件是已损坏的吗

**Comment by duobancc** [comment]
> 

是的，本地开发导出只是让我修复，修复后还是可以用的，打包到dev就直接是损坏的了

**Comment by duobancc** [comment]
local: 
![image](https://user-images.githubusercontent.com/37232082/165214252-fea2c0de-2dcf-4687-b1df-aec8044595a7.png)
dev: 
![image](https://user-images.githubusercontent.com/37232082/165214455-84423fb2-dd55-4645-bfab-1939bd1be749.png)

**Comment by duobancc** [comment]
我留个联系方式给你吧，github 老是抽风， qq, 3433310155
