### ISSUE TITLE
你好，最近使用发现设置导出excel样式没生效，默认的样式也没了

### ISSUE THREAD

**Issue by zhangguian** [PengChen96/table-xlsx#3]

**Comment by PengChen96** [comment]
你好，安装的table-xlsx和@pengchen/xlsx分别是什么版本，你这边是怎么设置样式的，是要设置哪个样式，方便贴下代码吗
https://pengchen96.github.io/table-xlsx/docs/tutorial-extras/export-style这个是简单示例

**Comment by zhangguian** [comment]
我安装的是最新版本的，我主要想设置表头单元格背景和字体大小。下边我的主要代码和导出结果
![image](https://user-images.githubusercontent.com/64180451/174243744-cc466c04-f499-4682-aabf-5d03b678433e.png)
![image](https://user-images.githubusercontent.com/64180451/174244041-0fb99b75-90fe-4b39-93ff-0ce38b050916.png)
![image](https://user-images.githubusercontent.com/64180451/174244139-af8efcd1-0c67-4918-ab46-0e59b35f083f.png)

**Comment by nevereverlky** [comment]
我也安装的最新版本，样式也没有生效

**Comment by PengChen96** [comment]
我刚测试了下@pengchen/xlsx最新版本样式是有点问题，你将@pengchen/xlsx回退到0.0.4版本，再试下，晚点我修复更新下

**Comment by PengChen96** [comment]
我修复了，你安装下新版本试下 table-xlsx@0.1.5

**Comment by nevereverlky** [comment]
可以实现某个单元格的样式吗

**Comment by PengChen96** [comment]
设置单个单元格的样式吗，可以说下你的要求。

**Comment by nevereverlky** [comment]
就比如说我想要每行的第一列有个颜色，或者其中一个单元格的内容比较重要，要标红

**Comment by PengChen96** [comment]
ok，我这周末写下，你可以到时关注下这个项目

**Comment by nevereverlky** [comment]
嗯嗯！就比如可能某几行的内容我想居中，其他不想居中这样子，辛苦啦~

**Comment by PengChen96** [comment]
发布了新版本0.1.6，新增了txHeaderCellStyle、onTxBodyCell、onTxBodyRow这几个参数设置样式，你可以试试。
这是两个示例：[设置单元格](https://pengchen96.github.io/table-xlsx/docs/tutorial-extras/export-cell-style)
[设置行](https://pengchen96.github.io/table-xlsx/docs/tutorial-extras/export-row-style)
