### ISSUE TITLE
数据为 null 的时候导出文件 有异常

### ISSUE THREAD

**Issue by OxOld** [PengChen96/table-xlsx#5]
使用：render: (value) => <>{value !== null ? value: '-'}</> 也无效。
![image](https://user-images.githubusercontent.com/49990116/183285200-1df44ec1-fce0-4e22-a168-ad985c3ab53f.png)
点击是 后 
![image](https://user-images.githubusercontent.com/49990116/183285220-2720622b-b219-4af5-97e5-de2e1479d369.png)

**Comment by OxOld** [comment]
![Uploading image.png…]()
数据源

**Comment by PengChen96** [comment]
你好，试试0.1.7-alpha.1这个版本，后续会更新到0.1.7

**Comment by OxOld** [comment]
非常好，包括 render 不生效也处理了
