### ISSUE TITLE
parseFile 报错

### ISSUE THREAD

**Issue by duobancc** [PengChen96/table-xlsx#7]
## 报错
![image](https://user-images.githubusercontent.com/37232082/222064277-c3e2b9ce-92f0-4d63-a353-3b75012af5f8.png)

## 原因
![image](https://user-images.githubusercontent.com/37232082/222064519-6c37eb20-94dc-4a2b-a96d-fc693ffcd7b1.png)
> ws['!merges'] 值为undefined

**Comment by PengChen96** [comment]
在0.1.9版本修复
