### ISSUE TITLE
能支持表头带斜线分割符的导出吗？要如何配置呢？

### ISSUE THREAD

**Issue by Longleggedmouse** [PengChen96/table-xlsx#8]
如一个表头单元格中通过分割线划分为多部分内容填充的，一般用于表格左上角展示的

**Comment by PengChen96** [comment]
没太明白，能再详细描述下吗，或者能给个示例吗

**Comment by Longleggedmouse** [comment]
就是一个单元内通过画斜线，划分多个区域，展示多个文字内容，比如画对角线线，然后在单元格右上展示文字参数，在单元格左下展示文字时间，可以这样嘛？

**Comment by PengChen96** [comment]
excel中要支持对角线吗，这个目前是不支持的，但可以通过useRender参数将文字内容都展示在一个单元格内

**Comment by Longleggedmouse** [comment]
好的好的，感谢解答
