### ISSUE TITLE
老版本的项目使用会报错误umi的发布者虽然有提到怎么解决应该是你发布es6没转es这个视频你可以看下 

### ISSUE THREAD

**Issue by ngwszsd** [PengChen96/table-xlsx#9]
老版本的项目使用会报错误umi的发布者虽然有提到怎么解决应该是你发布es6没转es这个视频你可以看下 https://www.youtube.com/watch?v=z4pWFpPiIoc    视频里面一分50秒的报错位置在你的包里找不到 帮忙看下是哪里没有转 谢谢啦
![image](https://user-images.githubusercontent.com/45424459/232480042-f9f8a626-2ced-48a9-ab8d-008adb7c939c.png)

**Comment by PengChen96** [comment]
你好，不好意思这个之前没看到消息，不知道你是否解决问题了。

**Comment by garvin-n** [comment]
解决了 但是最好还是加一下

> 你好，不好意思这个之前没看到消息，不知道你是否解决问题了。

解决了

**Comment by PengChen96** [comment]
> 解决了 但是最好还是加一下
> 
> > 你好，不好意思这个之前没看到消息，不知道你是否解决问题了。
> 
> 解决了 拴q

你是怎么解决的，方便在这分享下吗😄，感谢🌹

**Comment by ngwszsd** [comment]
> > 解决了 但是最好还是加一下
> > > 你好，不好意思这个之前没看到消息，不知道你是否解决问题了。
> > 
> > 
> > 解决了 拴q
> 
> 你是怎么解决的，方便在这分享下吗😄，感谢🌹
![image](https://github.com/PengChen96/table-xlsx/assets/45424459/24d1c99d-5ea4-4fae-91ad-cc2b5a64d4a6)
两种：1是按照图片配置，但是有概率build会失败 这样就解决不了了
2是到https://v3.umijs.org/zh-CN/docs/faq#%E7%AC%AC%E4%B8%83%E6%AD%A5%E3%80%81%E7%BB%99-es5-imcompatible-versions-%E6%8F%90-pr 这个库去提交pr  我提了但是还没人合并
可以看我开始留的那个youtu视频里面是umi发布者录的解决办法
